-- Create the 'users' table
CREATE TABLE users (
    user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama_lengkap VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('pengajar', 'siswa')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create the 'courses' table
CREATE TABLE courses (
    course_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama_course VARCHAR(255) NOT NULL,
    deskripsi TEXT,
    id_pengajar BIGINT REFERENCES users(user_id) ON DELETE SET NULL
);

-- Create the 'materials' table
CREATE TABLE materials (
    material_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_course BIGINT REFERENCES courses(course_id) ON DELETE CASCADE,
    judul_materi VARCHAR(255) NOT NULL,
    deskripsi TEXT,
    file_path TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create the 'assignments' table
CREATE TABLE assignments (
    assignment_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_course BIGINT REFERENCES courses(course_id) ON DELETE CASCADE,
    judul_tugas VARCHAR(255) NOT NULL,
    instruksi TEXT,
    due_date TIMESTAMPTZ
);

-- Create the 'submissions' table
CREATE TABLE submissions (
    submission_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_assignment BIGINT REFERENCES assignments(assignment_id) ON DELETE CASCADE,
    id_siswa BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    file_path TEXT,
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    nilai INT,
    feedback TEXT
);